/*
 * generated by Xtext 2.10.0
 */
package com.codebuilder


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CodeBuilderStandaloneSetup extends CodeBuilderStandaloneSetupGenerated {

	def static void doSetup() {
		new CodeBuilderStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
